sudo: required
dist: trusty
cache:
  yarn: true
notifications:
  email: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run semantic-release
  - npm run build
after_success:
  - npm run ngh
branches:
  only:
  - master
